---
title: Benefits and Costs of (Dual) Apprenticeship in an Informal Setting
author: 
  - name: Bart Kudrzycki
    affiliation: Development Economics Group, ETH Zurich, Switzerland, <bartlomiej.kudrzycki@nadel.ethz.ch>
date: \today
output: 
  bookdown::pdf_document2:
    latex_engine: xelatex
    template: template.tex
    extra_dependencies: ["flafter", "placeins"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,
                      warning=FALSE,
                      echo = FALSE, 
                      fig.path='figures/', 
                      floatfoot.envs = c("figure", "table", "longtabu")) 

options(scipen=2, digits=2)
```

```{r loadlibraries, include=FALSE}
suppressMessages(library(tidyverse))
library(bookdown)
library(gtsummary)
library(labelled)
suppressMessages(library(stargazer))
```

```{r loaddata, include=FALSE}
# rerun all code periodically
# source("../code/master.R")
load("../../data/df.rda")
# load functions
source("../../functions/add_by_n.R")
ggplot2::theme_set(ggplot2::theme_bw())  ## (sets the ggplot2 theme to theme_bw)
```

```{r appdesc}
df %>% select(age, sex, SELECTED, wave) %>%
  mutate(SELECTED = factor(SELECTED, levels = c(1, 0, 3),
                           labels = c('Selected', 'Not Selected', 'Did Not Apply')),
         sex = factor(sex, labels = c("Female", "Male")),
         wave = factor(wave, labels = c("Baseline", "Endline"))) %>% 
  rename("CQP Status" = SELECTED, "Age" = age, "Gender" = sex) %>% 
  tbl_summary(by=wave,
              type = list(Age ~ "continuous",
                          Gender ~ "categorical"),
              statistic = all_continuous() ~ c("{mean} ({sd})"),
              missing = "no") %>% 
  modify_header(label = "**Characteristic**") %>% 
  as_kable_extra(caption = "Apprentice Descriptive Statistics", 
                 booktabs = T,
                 linesep = "")
```

```{r firmdesc}
df %>% select(FS1.2, wave, FS4.1, firm_size, FS3.4, FS6.1, tidyselect::vars_select(names(df), matches("FS3.5"))) %>% 
  group_by(FS1.2, wave) %>% 
  summarise_all(mean, na.rm = T) %>% ungroup() %>% 
  mutate(wave = factor(wave, labels = c("Baseline", "Endline"))) %>% 
  rename("Firm size (computed)" = firm_size, 
         "Firm size (reported)" = FS3.4,
         "Months operational (past year)" = FS4.1,
         "Apprentices hired" = FS6.1,
         "Partners (incl. owner)" = FS3.5_1,
         "Permanent employees" = FS3.5_2,
         "Paid family workers" = FS3.5_3,
         "Unpaid family workers"  = FS3.5_4,
         "Occasional workers" = FS3.5_5) %>% 
  tbl_summary(by=wave,
              type = everything() ~ "continuous",
              digits = all_continuous() ~ 1,
              statistic = all_continuous() ~ c("{mean} ({sd})"),
              missing = "no",
              include = -FS1.2) %>% 
  add_stat(
    fns = everything() ~ add_by_n
  ) %>% 
  modify_table_body(
    ~ .x %>%
      dplyr::relocate(add_n_stat_1, .before = stat_1) %>%
      dplyr::relocate(add_n_stat_2, .before = stat_2)
  ) %>%
  modify_header(stat_by =  "**{level}**",
                starts_with("add_n_stat") ~ "**N**",
                label = "") %>% 
  add_p(all_continuous() ~ "paired.t.test", group = FS1.2) %>% 
  modify_header(label = "**Characteristic**") %>% 
  as_kable_extra(caption = "Firm Descriptive Statistics", 
                 booktabs = T,
                 linesep = "")
```

``` {r profits}
df %>% select(FS1.2, FS4.7, FS5.1, FS5.3, FS5.4, profits, wave) %>%
  group_by(FS1.2, wave) %>% summarise_at(c("FS4.7", "FS5.1", "FS5.3", "FS5.4", "profits"), mean, na.rm = T) %>% ungroup() %>% 
  mutate(wave = factor(wave, labels = c("Baseline", "Endline"))) %>% 
  tbl_summary(by=wave,
              type = everything() ~ "continuous",
              statistic = all_continuous() ~ c("{mean} ({sd})"),
              missing = "no",
              digits = list(everything() ~ c(0, 0)),
              include = -FS1.2,
              label = list(FS4.7 ~ "Revenues",
                           FS5.3 ~ "Total wages",
                           FS5.1 ~ "Non-wage expenses",
                           FS5.4 ~ "Profits (reported)",
                           profits ~ "Profits (calculated)"))  %>% 
  add_stat(
    fns = everything() ~ add_by_n
  ) %>% 
  modify_table_body(
    ~ .x %>%
      dplyr::relocate(add_n_stat_1, .before = stat_1) %>%
      dplyr::relocate(add_n_stat_2, .before = stat_2)
  ) %>%
  modify_header(stat_by =  "**{level}**",
                starts_with("add_n_stat") ~ "**N**",
                label = "") %>% 
  modify_footnote(
    all_stat_cols() ~ "Mean (SD). All accounts in FCFA."
  ) %>% 
  add_p(all_continuous() ~ "paired.t.test", group = FS1.2) %>% 
  as_kable_extra(caption = "Firm Accounting", 
                 booktabs = T,
                 linesep = "")
```


```{r wages}
df %>% select(contains("FS5.2"), wave, FS1.2) %>%
  mutate(wave = factor(wave, labels = c("Baseline", "Endline"))) %>% 
  group_by(FS1.2, wave) %>% summarise_all(mean, na.rm = T) %>% 
  tbl_summary(by=wave,
              type = everything() ~ "continuous",
              statistic = all_continuous() ~ c("{mean} ({sd})"),
              missing = "no",
              include = -FS1.2,
              digits = list(everything() ~ c(0, 0)),
              label = list(FS5.2_1_7 ~ "Firm owner",
                           FS5.2_1_1 ~ "Former apprentice (diff. workshop)",
                           FS5.2_1_2 ~ "Former apprentice (same workshop)",
                           FS5.2_1_3 ~ "Worker with secondary educ. or more",
                           FS5.2_1_4 ~ "Worker with primary educ. or less",
                           FS5.2_1_5 ~ "Paid family worker",
                           FS5.2_1_6 ~ "Occassional worker",
                           FS5.2_1_8 ~ "Traditional apprentice (first year)",
                           FS5.2_1_9 ~ "Traditional apprentice (third year)",
                           FS5.2_1_10 ~ "CQP apprentice (first year)",
                           FS5.2_1_11 ~ "CQP apprentice (third year)"))  %>% 
  add_stat(
    fns = everything() ~ add_by_n
  ) %>% 
  modify_table_body(
    ~ .x %>%
      dplyr::relocate(add_n_stat_1, .before = stat_1) %>%
      dplyr::relocate(add_n_stat_2, .before = stat_2)
  ) %>%
  modify_header(stat_by =  "**{level}**",
                starts_with("add_n_stat") ~ "**N**",
                label = "") %>% 
  modify_footnote(
    all_stat_cols() ~ "Mean (SD). Monthly wages in FCFA."
  ) %>% 
  as_kable_extra(caption = "Wages", 
                 booktabs = T,
                 linesep = "")
```

```{r skills}
df %>% select(contains("skills"), wave, IDYouth) %>%
  mutate(wave = factor(wave, labels = c("Baseline", "Endline"))) %>% 
  tbl_summary(by=wave,
              type = everything() ~ "continuous",
              statistic = all_continuous() ~ c("{mean} ({sd})"),
              missing = "no",
              include = -IDYouth) %>% 
      add_stat(
    fns = everything() ~ add_by_n
  ) %>% 
  modify_table_body(
    ~ .x %>%
      dplyr::relocate(add_n_stat_1, .before = stat_1) %>%
      dplyr::relocate(add_n_stat_2, .before = stat_2)
  ) %>%
  add_p(all_continuous() ~ "paired.t.test", group = IDYouth) %>% 
  modify_header(stat_by =  "**{level}**",
                starts_with("add_n_stat") ~ "**N**",
                label = "**Trade**") %>% 
  modify_footnote(
    all_stat_cols() ~ "Mean (SD). Proportion of correct apprentice answers to knowledge questions."
  ) %>% 
  as_kable_extra(caption = "Change in Apprentice Knowledge", 
                 booktabs = T,
                 linesep = "")
```

```{r compexp1}
comp <- df %>% select(contains("comp"), -contains("a_"), wave, IDYouth) %>%
  mutate(wave = factor(wave, labels = c("Baseline", "Endline"))) %>% 
  tbl_summary(by=wave,
              type = everything() ~ "continuous",
              statistic = all_continuous() ~ c("{mean} ({sd})"),
              missing = "no",
              include = -IDYouth) %>% 
    add_stat(
    fns = everything() ~ add_by_n
  ) %>% 
  modify_table_body(
    ~ .x %>%
      dplyr::relocate(add_n_stat_1, .before = stat_1) %>%
      dplyr::relocate(add_n_stat_2, .before = stat_2)
  ) %>%
  add_p(all_continuous() ~ "paired.t.test", group = IDYouth) %>% 
  modify_header(stat_by =  "**{level}**",
                starts_with("add_n_stat") ~ "**N**",
                label = "**Trade**") %>% 
  modify_footnote(
    all_stat_cols() ~ "Mean (SD). Proportion of tasks reported by firm."
  )

exp <- df %>% select(contains("exp"), -contains("a_"), wave, IDYouth) %>%
  mutate(wave = factor(wave, labels = c("Baseline", "Endline"))) %>% 
  tbl_summary(by=wave,
              type = everything() ~ "continuous",
              statistic = all_continuous() ~ c("{mean} ({sd})"),
              missing = "no",
              include = -IDYouth) %>% 
  add_stat(
    fns = everything() ~ add_by_n
  ) %>% 
  modify_table_body(
    ~ .x %>%
      dplyr::relocate(add_n_stat_1, .before = stat_1) %>%
      dplyr::relocate(add_n_stat_2, .before = stat_2)
  ) %>%
  add_p(all_continuous() ~ "paired.t.test", group = IDYouth) %>%  
  modify_header(stat_by =  "**{level}**",
                starts_with("add_n_stat") ~ "**N**",
                label = "**Trade**") %>% 
  modify_footnote(
    all_stat_cols() ~ "Mean (SD). Proportion of tasks reported by firm."
  )

tbl_stack(list(comp, exp), group_header = c("Competencies", "Experience"), quiet = TRUE) %>% 
  as_kable_extra(caption = "Firm Evaluations of Apprentice Skill Over Time", 
                 booktabs = T,
                 linesep = "")
```

```{r compexp2}
x <- df %>% filter(wave == 1, SELECTED != 3) %>% pivot_longer(cols = contains("comp")) %>% mutate(side = ifelse(grepl("a_", name), "Apprentice", "Firm")) %>% mutate(name = str_remove_all(name, "a_")) %>% select(c(IDYouth, side, name, value)) %>% pivot_wider()

x <- x %>% left_join(df %>% filter(wave == 1, SELECTED != 3) %>% pivot_longer(cols = contains("exp")) %>% mutate(side = ifelse(grepl("a_", name), "Apprentice", "Firm")) %>% mutate(name = str_remove_all(name, "a_")) %>% select(c(IDYouth, side, name, value)) %>% pivot_wider(), by = c("IDYouth", "side")) %>% mutate(ID = row_number())

var_label(x$comp_elec) <- "Electrical Installation"
var_label(x$comp_macon) <- "Masonry"
var_label(x$comp_menuis) <- "Carpentry"
var_label(x$comp_plomb) <- "Plumbing"
var_label(x$comp_metal) <- "Metalwork"
var_label(x$comp_all_trades) <- "Overall"
var_label(x$exp_elec) <- "Electrical Installation"
var_label(x$exp_macon) <- "Masonry"
var_label(x$exp_menuis) <- "Carpentry"
var_label(x$exp_plomb) <- "Plumbing"
var_label(x$exp_metal) <- "Metalwork"
var_label(x$exp_all_trades) <- "Overall"

comp <- x %>% select(tidyselect::vars_select(names(x), matches("comp")), side, ID) %>% 
  tbl_summary(by=side,
              type = everything() ~ "continuous",
              statistic = all_continuous() ~ c("{mean} ({sd})"),
              digits = all_continuous() ~ 2,
              missing = "no",
              include = -ID) %>% 
      add_stat(
    fns = everything() ~ add_by_n
  ) %>% 
  modify_table_body(
    ~ .x %>%
      dplyr::relocate(add_n_stat_1, .before = stat_1) %>%
      dplyr::relocate(add_n_stat_2, .before = stat_2)
  ) %>%
  modify_header(stat_by =  "**{level}**",
                starts_with("add_n_stat") ~ "**N**",
                label = "**Trade**") %>% 
  modify_footnote(
    all_stat_cols() ~ "Mean (SD). Proportion of tasks reported by apprentices and firms at endline.")

exp <- x %>% select(tidyselect::vars_select(names(x), matches("exp")), side, IDYouth) %>% 
  tbl_summary(by=side,
              type = everything() ~ "continuous",
              statistic = all_continuous() ~ c("{mean} ({sd})"),
              missing = "no",
              include = -IDYouth) %>% 
  add_stat(
    fns = everything() ~ add_by_n
  ) %>% 
  modify_table_body(
    ~ .x %>%
      dplyr::relocate(add_n_stat_1, .before = stat_1) %>%
      dplyr::relocate(add_n_stat_2, .before = stat_2)
  ) %>%
  modify_header(stat_by =  "**{level}**",
                starts_with("add_n_stat") ~ "**N**",
                label = "**Trade**") %>% 
  modify_footnote(
    all_stat_cols() ~ "Mean (SD). Proportion of tasks reported by apprentices and firms at endline.")

tbl_stack(list(comp, exp), group_header = c("Competencies", "Experience"), quiet = TRUE) %>% 
  as_kable_extra(caption = "Firm vs. Self-reported Evaluations of Apprentice Skill", 
                 booktabs = T,
                 linesep = "")

```

```{r compexpdiff}
comp <- df %>% select(contains("comp"), -contains("a_"), wave, IDYouth, SELECTED) %>%
  pivot_wider(names_from = wave,
              values_from = contains("comp")) %>%
  mutate(comp_elec = comp_elec_1-comp_elec_0,
         comp_macon = comp_macon_1-comp_macon_0,
         comp_menuis = comp_menuis_1-comp_menuis_0,
         comp_plomb = comp_plomb_1-comp_plomb_0,
         comp_metal = comp_metal_1-comp_metal_0) %>%
  select(comp_elec, comp_macon, comp_menuis, comp_plomb, comp_metal, SELECTED) %>% 
  mutate(SELECTED = factor(SELECTED, levels = c(1, 0, 3),
                           labels = c('Selected', 'Not Selected', 'Did Not Apply'))) %>% 
  tbl_summary(by=SELECTED,
              type = everything() ~ "continuous",
              statistic = all_continuous() ~ c("{mean} ({sd})"),
              missing = "no") %>% 
  add_stat(
    fns = everything() ~ add_by_n
  ) %>% 
  modify_table_body(
    ~ .x %>%
      dplyr::relocate(add_n_stat_1, .before = stat_1) %>%
      dplyr::relocate(add_n_stat_2, .before = stat_2) %>% 
      dplyr::relocate(add_n_stat_3, .before = stat_3)
  ) %>%
  modify_header(stat_by =  "**{level}**",
                starts_with("add_n_stat") ~ "**N**",
                label = "**Trade**") %>% 
  modify_footnote(
    all_stat_cols() ~ "Mean (SD). Change in scores over time."
  ) 

exp <- df %>% select(contains("exp"), -contains("a_"), wave, IDYouth, SELECTED) %>%
  pivot_wider(names_from = wave,
              values_from = contains("exp")) %>%
  mutate(exp_elec = exp_elec_1-exp_elec_0,
         exp_macon = exp_macon_1-exp_macon_0,
         exp_menuis = exp_menuis_1-exp_menuis_0,
         exp_plomb = exp_plomb_1-exp_plomb_0,
         exp_metal = exp_metal_1-exp_metal_0) %>%
  select(exp_elec, exp_macon, exp_menuis, exp_plomb, exp_metal, SELECTED) %>% 
  mutate(SELECTED = factor(SELECTED, levels = c(1, 0, 3),
                           labels = c('Selected', 'Not Selected', 'Did Not Apply'))) %>% 
  tbl_summary(by=SELECTED,
              type = everything() ~ "continuous",
              statistic = all_continuous() ~ c("{mean} ({sd})"),
              missing = "no") %>% 
  add_stat(
    fns = everything() ~ add_by_n
  ) %>% 
  modify_table_body(
    ~ .x %>%
      dplyr::relocate(add_n_stat_1, .before = stat_1) %>%
      dplyr::relocate(add_n_stat_2, .before = stat_2) %>% 
      dplyr::relocate(add_n_stat_3, .before = stat_3)
  ) %>%
  modify_header(stat_by =  "**{level}**",
                starts_with("add_n_stat") ~ "**N**",
                label = "**Trade**") %>% 
  modify_footnote(
    all_stat_cols() ~ "Mean (SD). Change in proportion of tasks over time."
  )

tbl_stack(list(comp, exp), group_header = c("Comp.", "Exp."), quiet = TRUE) %>% 
  as_kable_extra(caption = "Changes in competency and experience scores by CQP status", 
                 booktabs = T,
                 linesep = "",
                 position = "H")

```

```{r allow}
df %>% select(wave, "allow_pocket_money", "allow_food", "allow_transport", "all_allowances", IDYouth) %>% 
  mutate(wave = factor(wave, labels = c("Baseline", "Endline"))) %>% 
  tbl_summary(by=wave,
              type = everything() ~ "continuous",
              statistic = all_continuous() ~ c("{mean} ({sd})"),
              missing = "no",
              include = -IDYouth) %>% 
  add_stat(
    fns = everything() ~ add_by_n
  ) %>% 
  modify_table_body(
    ~ .x %>%
      dplyr::relocate(add_n_stat_1, .before = stat_1) %>%
      dplyr::relocate(add_n_stat_2, .before = stat_2)
  ) %>%
  modify_header(stat_by =  "**{level}**",
                starts_with("add_n_stat") ~ "**N**",
                label = "**Trade**") %>% 
  add_p(all_continuous() ~ "paired.t.test", group = IDYouth) %>% 
   modify_footnote(
    all_stat_cols() ~ "Mean (SD). Allowances reported in FCFA by firm."
  ) %>% 
  as_kable_extra(caption = "Apprentice Allowances", 
                 booktabs = T,
                 linesep = "")

```


```{r fees1}
df %>% select(contains("fee"), wave, -contains("a_"), IDYouth) %>% 
  mutate(wave = factor(wave, labels = c("Baseline", "Endline"))) %>% 
  tbl_summary(by=wave,
              type = everything() ~ "continuous",
              statistic = all_continuous() ~ c("{mean} ({sd})"),
              missing = "no",
              include = -IDYouth) %>% 
  add_stat(
    fns = everything() ~ add_by_n
  ) %>% 
  modify_table_body(
    ~ .x %>%
      dplyr::relocate(add_n_stat_1, .before = stat_1) %>%
      dplyr::relocate(add_n_stat_2, .before = stat_2)
  ) %>%
  modify_header(stat_by =  "**{level}**",
                starts_with("add_n_stat") ~ "**N**",
                label = "**Trade**") %>% 
  add_p(all_continuous() ~ "paired.t.test", group = IDYouth) %>% 
   modify_footnote(
    all_stat_cols() ~ "Mean (SD). Fees reported in FCFA by firm."
  ) %>% 
  as_kable_extra(caption = "Apprenticeship fees reported by firm.", 
                 booktabs = T,
                 linesep = "")

```

```{r fees2}
df <- unlabelled(df)

x <- df %>% select(-"fees_avg") %>% pivot_longer(cols = contains("fee")) %>% mutate(side = ifelse(grepl("a_", name), "Apprentice", "Firm")) %>% mutate(name = str_remove_all(name, "a_")) %>% select(c(IDYouth, wave, side, name, value)) %>% pivot_wider() 

var_label(x$fee_entry) <- "Initiation"
var_label(x$fee_formation) <- "Training"
var_label(x$fee_liberation) <- "Graduation"
var_label(x$fee_materials) <- "Materials"
var_label(x$fee_contract) <- "Contract"
var_label(x$fee_application) <- "Application"
var_label(x$total_fees) <- "Total"

baseline <- x %>% filter(wave == 0) %>% 
  tbl_summary(by=side,
              type = everything() ~ "continuous",
              statistic = all_continuous() ~ c("{mean} ({sd})"),
              missing = "no",
              digits = list(everything() ~ c(0, 0)),
              include = -c(IDYouth, wave)) %>% 
  modify_header(stat_by =  "**{level}**",
                starts_with("add_n_stat") ~ "**N**",
                label = "**Fee Type**") %>% 
   modify_footnote(
    all_stat_cols() ~ "Mean (SD). Fees in FCFA."
  )

endline <- x %>% filter(wave == 1) %>% 
  tbl_summary(by=side,
              type = everything() ~ "continuous",
              statistic = all_continuous() ~ c("{mean} ({sd})"),
              missing = "no",
              digits = list(everything() ~ c(0, 0)),
              include = -c(IDYouth, wave)) %>% 
  modify_header(stat_by =  "**{level}**",
                starts_with("add_n_stat") ~ "**N**",
                label = "**Fee Type**") %>% 
   modify_footnote(
    all_stat_cols() ~ "Mean (SD). Fees in FCFA."
  )

tbl_merge(list(baseline, endline), tab_spanner = c("**Baseline**", "**Endline**")) %>% 
  as_kable_extra(caption = "Apprenticeship fees reported by apprentices and firm owners.", 
                 booktabs = T,
                 linesep = "")
```

```{r skillsreg, results = 'asis'}
m1 <- lm(skills_all_trades ~ factor(SELECTED) + duration, data = df)
m2 <- lm(skills_all_trades ~ factor(SELECTED) + duration + factor(FS1.2), data = df)
m3 <- lm(skills_all_trades ~ factor(SELECTED) + duration + firm_size + FS6.1 + dossier_selected + factor(FS1.2), data = df)
m4 <- lm(skills_all_trades ~ factor(SELECTED) + duration + firm_size + FS6.1 + dossier_selected + FS6.8 + FS6.9 + FS6.10 + ext_training + factor(FS1.2), data = df)

stargazer(m1, m2, m3, m4, omit = "FS1.2", df = FALSE, model.names = FALSE, model.numbers = FALSE, no.space = TRUE, digits = 2, header = F,
          covariate.labels = c("CQP",
                     "Years in training",
                     "Firm size",
                     "Total apprentices hired",
                     "CQP apprentices hired",
                     "Total instructors in firm",
                     "Days trained per week",
                     "Duration of last training",
                     "External training dummy"),
          dep.var.labels = "Fraction of knowledge questions",
          add.lines = list(c("Firm FE", "NO", "YES", "YES", "YES")))
```

```{r cbreg, results = 'asis'}
df$did <- df$SELECTED * df$wave
x <- df %>% filter(SELECTED != 3)

m1 <- lm(cb_simple ~ factor(SELECTED) + factor(FS1.2), data = x)
m2 <- lm(cb_simple ~ factor(SELECTED) + factor(FS1.2), data = df)
m3 <- lm(cb_simple ~ factor(SELECTED) + duration + factor(FS1.2), data = df)
m4 <- lm(cb_simple ~ factor(SELECTED) + duration + did + factor(FS1.2), data = df)

stargazer(m1, m2, m3, m4, omit = "FS1.2", df = FALSE, model.names = FALSE, model.numbers = FALSE, no.space = TRUE, digits = 0, header = F,
          covariate.labels = c("Selected for CQP",
                               "Applied but not selected",
                               "Years in Training",
                               "CQP * wave"),
          dep.var.labels = "Net Benefits to Firm",
          add.lines = list(c("Firm FE", "YES", "YES", "YES", "YES")))
```

```{r compreg, results = 'asis'}
df$cqp_dummy <- ifelse(df$SELECTED == 1, 1, 0)
df$did <- df$wave * df$cqp_dummy

m1 <- lm(comp_all_trades ~ factor(SELECTED), data = df)
m2 <- lm(comp_all_trades ~ factor(SELECTED) + factor(FS1.2), data = df)
m3 <- lm(comp_all_trades ~ factor(SELECTED) + did + factor(FS1.2), data = df)
m4 <- lm(comp_all_trades ~ factor(SELECTED) + did + duration + factor(FS1.2), data = df)
m5 <- lm(comp_all_trades ~ factor(SELECTED) + did + duration + firm_size + FS6.1 + dossier_selected + factor(FS1.2), data = df) #FS6.1: number apprentices
m6 <- lm(comp_all_trades ~ factor(SELECTED) + did + duration + firm_size + FS6.1 + dossier_selected + FS6.8 + FS6.9 + FS6.10 + ext_training + factor(FS1.2), data = df)


stargazer(m1, m2, m3, m4, m5, m6, omit = "FS1.2", df = FALSE, model.names = FALSE, model.numbers = FALSE,
          no.space = TRUE, digits = 3, header = F, table.placement = "H",
          covariate.labels = c("CQP participant",
                               "Did not apply for CQP",
                               "CQP x wave",
                               "Years in training",
                               "Firm size",
                               "Total apprentices",
                               "CQP apprentices",
                               "Total instructors",
                               "Days trained per week",
                               "Duration, last training",
                               "External training"),
          dep.var.labels = "Fraction of tasks - competency",
          add.lines = list(c("Firm FE", "NO", "YES", "YES", "YES", "YES", "YES")))
```
```{r cbreg, results = 'asis'}
df$did <- df$SELECTED * df$wave
x <- df %>% filter(SELECTED != 3)

m1 <- lm(cb_simple ~ factor(SELECTED) + factor(FS1.2), data = x)
m2 <- lm(cb_simple ~ factor(SELECTED) + factor(FS1.2), data = df)
m3 <- lm(cb_simple ~ factor(SELECTED) + duration + factor(FS1.2), data = df)
m4 <- lm(cb_simple ~ factor(SELECTED) + duration + did + factor(FS1.2), data = df)

stargazer(m1, m2, m3, m4, omit = "FS1.2", df = FALSE, model.names = FALSE, model.numbers = FALSE,
          no.space = TRUE, digits = 0, header = F, table.placement = "H",
          covariate.labels = c("Selected for CQP",
                               "Applied but not selected",
                               "Years in Training",
                               "CQP * wave"),
          dep.var.labels = "Net Benefits to Firm",
          add.lines = list(c("Firm FE", "YES", "YES", "YES", "YES")))
```


$$ \begin{aligned} \textit{firm_profits_endline} - \textit{firm_profits_baseline}  =  \beta_1\textit{CQP_apprentices}\end{aligned} + \beta_2(\textit{total_apprentices_endline} - \textit{total_apprentices_baseline}) + \beta_3\textit{firm size at baseline}$$

